FROM docker:27.5.0-alpine3.21
RUN apk add git openssh python3 py-pip
COPY ./requirements.txt .
RUN pip install --break-system-packages -r requirements.txt
WORKDIR /app
COPY ./entrypoint_build.sh .
RUN chmod +x entrypoint_build.sh
ENTRYPOINT "/app/entrypoint_build.sh"

