FROM python:3.9-slim

WORKDIR /app

# install git, ssh
RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    openssh-client \
    docker-compose \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

COPY builder.py /app/

ENTRYPOINT ["python3", "builder.py"]
