version: '3.8'

networks:
  app_network:
    driver: bridge

volumes:
  shared-socket:

secrets:
  my_email:
    file: /conf/email
  my_password:
    file: /conf/emailpass

services:
  billing-service:
    build:
      context: ../Billing
      dockerfile: docker-compose.yaml
    container_name: billing-service
    networks:
      - app_network
    depends_on:
      - weight-service
    volumes:
      - shared-socket:/socket

  weight-service:
    build:
      context: ../Weight
      dockerfile: docker-compose.yml
    container_name: weight-service
    networks:
      - app_network
    volumes:
      - shared-socket:/socket

  app-service:
    build: .
    container_name: app-service
    networks:
      - app_network
    depends_on:
      - billing-service
      - weight-service
    volumes:
      - shared-socket:/socket
    secrets:
      - my_email
      - my_password

# test comment
