version: '3.9'

services:
  billing-server:
    build:
      context: .  # Backend folder
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    depends_on:
      - db
    environment:
      - DB_USER=root
      - DB_PASSWORD=adminpass
      - DB_HOST=db
      - DB_NAME=billdb
      - PYTHONPATH=.
    restart: always
    volumes:
      - .:/app
      - ./in:/app/in
    networks:
      app_network:
        ipv4_address: 192.168.2.2

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: adminpass
      MYSQL_DATABASE: billdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      app_network:
        ipv4_address: 192.168.2.3

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://192.168.2.2:5000  # Build-time environment variable
    environment:
      - VITE_API_URL=http://192.168.2.2:5000  # Runtime environment variable
    ports:
      - "3000:3000"
    depends_on:
      - billing-server
    networks:
      app_network:
        ipv4_address: 192.168.2.4

volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.2.0/24

