version: '3.8'

services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root123
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    container_name: weight_mysql

volumes:
  mysql_data:
    driver: local