version: '3.8'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: weight
      MYSQL_USER: nati
      MYSQL_PASSWORD: bashisthebest
    volumes:
      - ./app/weightdb.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    container_name: weight_mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot123"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  flask_app:
    image: python:3.9-slim
    volumes:
      - ./app:/app
      - ./app/in:/app/in
    working_dir: /app
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=mysql
      - DB_USER=nati
      - DB_PASSWORD=bashisthebest
      - DB_NAME=weight
      - DB_PORT=3306
      - FLASK_DEBUG=1  #  enable debug mode for Auto reloading python Flask app upon code changes
    depends_on:
      mysql:
        condition: service_healthy
    container_name: weight_flask
    command: >
      bash -c "apt-get update && 
      apt-get install -y netcat-traditional && 
      pip install -r requirements.txt &&
      echo 'Waiting for MySQL...' &&
      while ! nc -z mysql 3306; do
        echo 'MySQL not ready - sleeping 5s' &&
        sleep 5;
      done &&
      echo 'MySQL is up - starting app' &&
      flask run --host=0.0.0.0 --port=5000 --reload"  # --reload flag for reloading python Flask app upon code changes

volumes:
  mysql_data: